[package]
name = "engine_panic"
version = "0.0.1"
description = "An example EinsteinDB causetStorage engine that does nothing but panic"
edition = "2018"
publish = false

[deplightlikeencies]
edb = { path = "../edb" }
edb_alloc = { path = "../edb_alloc" }
# FIXME: Remove this dep from the edb interface
edb_util = { path = "../edb_util" }
