[package]
name = "engine_panic"
version = "0.0.1"
description = "An example EinsteinDB causetStorage engine that does nothing but panic"
edition = "2018"
publish = false

[deplightlikeencies]
engine_promises = { path = "../engine_promises" }
einsteindb-prod_alloc = { path = "../einsteindb-prod_alloc" }
# FIXME: Remove this dep from the engine_promises interface
einsteindb-prod_util = { path = "../einsteindb-prod_util" }
