[package]
name = "configuration_derive"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
proc-macro = true

[deplightlikeencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["extra-promises", "full"] }
