[package]
name = "profiler"
version = "0.0.1"
edition = "2018"
publish = false

[features]
profiling = ["lazy_static", "gperftools", "callgrind", "valgrind_request"]

[deplightlikeencies]
einsteindb_alloc = { path = "../einsteindb_alloc" }

[target.'causet(unix)'.deplightlikeencies]
lazy_static = { version = "1.3.0", optional = true }
gperftools = { version = "0.2.0", optional = true }
callgrind = { version = "1.1.0", optional = true }
valgrind_request = { version = "1.1.0", optional = true }

[[example]]
name = "prime"
required-features = ["profiling"]
