[package]
name = "milevadb_query_codegen"
version = "0.0.1"
edition = "2018"
publish = false

[lib]
proc-macro = true

[deplightlikeencies]
darling = "0.10"
heck = "0.3"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-promises"] }
